import {
  User,
  FolderOpen,
  Briefcase,
  GraduationCap,
  BarChart3,
} from "lucide-react";

export const managementLinks = [
  {
    id: "infos",
    title: "Update Infos",
    description: "Edit personal information & bio",
    href: "/admin/dashboard/infos",
    icon: User,
    gradient: "from-pink-500 to-violet-600",
    glowColor: "pink-500/30",
    count: null,
  },
  {
    id: "projects",
    title: "Manage Projects",
    description: "Add, edit & organize projects",
    href: "/admin/dashboard/projects",
    icon: FolderOpen,
    gradient: "from-[#16f2b3] to-cyan-400",
    glowColor: "[#16f2b3]/30",
    count: 12,
  },
  {
    id: "experiences",
    title: "Manage Experiences",
    description: "Update work & education history",
    href: "/admin/dashboard/experiences",
    icon: Briefcase,
    gradient: "from-violet-500 to-purple-600",
    glowColor: "violet-500/30",
    count: 8,
  },
  {
    id: "educations",
    title: "Manage Educations",
    description: "Add and update education details",
    href: "/admin/dashboard/educations",
    icon: GraduationCap,
    gradient: "from-green-500 to-emerald-500",
    glowColor: "green-500/30",
    count: 4,
  },
  {
    id: "analytics",
    title: "Analytics",
    description: "View visitor stats & metrics",
    href: "/admin/dashboard/analytics",
    icon: BarChart3,
    gradient: "from-blue-500 to-indigo-600",
    glowColor: "blue-500/30",
    count: null,
  },
];
