import {
  FaBriefcase,
  FaChartBar,
  FaFileAlt,
  FaGraduationCap,
  FaProjectDiagram,
  FaUser,
} from "react-icons/fa";

export const managementLinks = [
  {
    id: "infos",
    title: "Update Infos",
    description: "Edit personal information & bio",
    href: "/admin/dashboard/infos",
    icon: FaUser,
    gradient: "from-pink-500 to-violet-600",
    glowColor: "pink-500/30",
  },
  {
    id: "projects",
    title: "Manage Projects",
    description: "Add, edit & organize projects",
    href: "/admin/dashboard/projects",
    icon: FaProjectDiagram,
    gradient: "from-[#16f2b3] to-cyan-400",
    glowColor: "[#16f2b3]/30",
  },
  // {
  //   id: "experiences",
  //   title: "Manage Experiences",
  //   description: "Update work & education history",
  //   href: "/admin/dashboard/experiences",
  //   icon: FaBriefcase,
  //   gradient: "from-violet-500 to-purple-600",
  //   glowColor: "violet-500/30",
  // },
  // {
  //   id: "educations",
  //   title: "Manage Educations",
  //   description: "Add and update education details",
  //   href: "/admin/dashboard/educations",
  //   icon: FaGraduationCap,
  //   gradient: "from-green-500 to-emerald-500",
  //   glowColor: "green-500/30",
  // },
  // {
  //   id: "analytics",
  //   title: "Analytics",
  //   description: "View visitor stats & metrics",
  //   href: "/admin/dashboard/analytics",
  //   icon: FaChartBar,
  //   gradient: "from-blue-500 to-indigo-600",
  //   glowColor: "blue-500/30",
  // },
  // {
  //   id: "cv",
  //   title: "CV Settings",
  //   description: "Update resume & download settings",
  //   href: "/admin/dashboard/cv",
  //   icon: FaFileAlt,
  //   gradient: "from-orange-500 to-red-500",
  //   glowColor: "orange-500/30",
  // },
];
